Character/scientist
bernas670/xtravaganza pull request #44
Opened 2021-06-05 22:13 UTC by claudiarmamede

2021-06-07 16:04 UTC, CajoAlbuquerque approved these changes
I am approving because everything seems fine. I have not tested the game as that would drain my battery really quick. Consider the above comment, but if you think it is better to implement it in another branch than I'm ok with it as well

2021-06-07 16:04 UTC, CajoAlbuquerque commented on Assets/Scripts/Player/Player.cs
> +        }
The texture is already in the repo. Changing the albedo of the Material programatically should be enough. We can also create a whole new material with the evil tezture and just swap materials mid game. No need to worry about smooth transitions! I guess the latter options is easier. Can you implement this in this branch right away?

2021-06-07 21:47 UTC, bernas670 requested changes
I noticed a little detail, when the scientist is dying he keeps moving away from the player. I had a similar problem when adding animations to the soldier. When you use the `communicateDeath` just set a `boolean` in the `ScientistController` so he does not move.
Other than that great job!

2021-06-08 09:07 UTC, BernardoCMoreira commented
> I noticed a little detail, when the scientist is dying he keeps moving away from the player. I had a similar problem when adding animations to the soldier. When you use the `communicateDeath` just set a `boolean` in the `ScientistController` so he does not move.
> Other than that great job!

Yeah thanks bernas! It's done

2021-06-09 13:38 UTC, bernas670 approved these changes
Lgtm! :ship:

2021-06-10 19:28 UTC, merged